# Generated by Django 2.2.7 on 2019-11-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=20)),
                ('arguments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('ip', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('commands', models.ManyToManyField(to='c2.command')),
            ],
        ),
    ]
