# Generated by Django 2.2.7 on 2019-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastBeacon',
            field=models.IntegerField(default=0),
        ),
    ]
