# Generated by Django 2.2.7 on 2019-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0002_client_lastbeacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='highTime',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='client',
            name='lowTime',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='maxFails',
            field=models.IntegerField(default=10),
        ),
    ]
